- Gemfile
- Gemfile.lock
- app/models/user.rb
- app/views/layouts/application.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- config/puma.rb
- config/routes.rb
- db/migrate/20200523130652_devise_create_users.rb
- db/schema.rb
- test/models/user_test.rb
Installation de la partie utilisateurs
> install devise

- app/models/product.rb
- db/migrate/20200523140219_create_products.rb
- db/schema.rb
- test/models/product_test.rb
> add product model

- app/models/booking.rb
- app/models/product.rb
- app/models/user.rb
- db/migrate/20200523140219_create_products.rb
- db/migrate/20200523142112_create_bookings.rb
- db/schema.rb
- test/models/booking_test.rb
add model booking and validates
> add model booking and validates

- db/migrate/20200525172842_add_name_to_users.rb
- db/schema.rb
> ajout colonne firstname

- db/migrate/20200525174822_add_column_users.rb
- db/schema.rb
> ajout colonne sur users

- app/models/product.rb
- app/models/user.rb
> correction models

- app/controllers/products_controller.rb
> add products controller

- app/controllers/products_controller.rb
- app/views/products/index.html.erb
- db/schema.rb
> add index view to products controller

- app/controllers/products_controller.rb
- app/views/products/_form.html.erb
- app/views/products/new.html.erb
> add_index_view_to_products_controller

- config/routes.rb
j'ai ajouté la route bookings.
Par contre je me demande s'il faut imbriquer bookings à products car la réservation se fait sur l'objet.
J'attend votre retour.
> ajout de la route bookings

- app/controllers/application_controller.rb
- app/controllers/bookings_controller.rb
- app/views/bookings/new.html.erb
- config/routes.rb
- db/migrate/20200526213619_change_value_column_bookings_table.rb
- db/schema.rb
- test/controllers/bookings_controller_test.rb
j'ai ajouté le controller de bookings
j'ai modifié la routes (nested avec products)
j'ai modifié le type des colonnes start_date et end_date (datetime => date)
> add bookings controller and routes

- app/controllers/pages_controller.rb
> correction bug

- app/controllers/products_controller.rb
- app/views/products/_form.html.erb
- app/views/products/new.html.erb
> ajout_product

- app/views/pages/home.html.erb
> contenu 2eme container de la home supprimé

- app/views/products/show.html.erb
- db/seeds.rb
> add_price_to_show

- .gitignore
- app/controllers/admin/products_controller.rb
- app/controllers/bookings_controller.rb
- app/controllers/products_controller.rb
- app/views/admin/products/index.html.erb
- app/views/products/show.html.erb
- config/routes.rb
> routes admin

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_card.scss
- app/views/pages/home.html.erb
- app/views/products/index.html.erb
- app/views/products/show.html.erb
- app/views/shared/_navbar.html.erb
> show_and_navbar

- app/assets/stylesheets/components/_show.scss
- app/views/products/show.html.erb
> suite modification show css

- app/views/pages/home.html.erb
> modification_search

- app/assets/stylesheets/components/_banner.scss
- app/views/pages/home.html.erb
> add container s/ 3 derniers article

- app/views/pages/home.html.erb
> reduc_barre

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
> modif navbar
